name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.7
    - run: julia -e '
            using Pkg; Pkg.add("Franklin");
            using Franklin;
            cd("doc");
            Pkg.activate("."); Pkg.instantiate();
            optimize(minify=false, prerender=false);'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/__site
